markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
baseurl: ""

version: 3.0.0

sass:
  # sass_dir: 
  style: compressed

github:
  repo: https://github.com/mdo/preboot
